package model;
// Generated 23/03/2016 04:10:05 AM by Hibernate Tools 4.3.1



/**
 * Comentario generated by hbm2java
 */
public class Comentario  implements java.io.Serializable {


     private String correo;
     private Usuario usuario;
     private String contenido;

    public Comentario() {
    }

	
    public Comentario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Comentario(Usuario usuario, String contenido) {
       this.usuario = usuario;
       this.contenido = contenido;
    }
   
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }




}


